### ISSUE TITLE
Change the way you create the database and tables

### ISSUE THREAD

**Issue by andresprogramacion123** [jod35/FastAPI-SQLModel-crash-course#2]
Hi man, I'm working with fastapi and sqlmodel to develop a rest api.
Observing your way of working I see that to create the database you have to execute the created_db.py module.
Looking at the official sqlmodel page they propose to create the database and tables using the "starup" event provided by fastapi.
(attached link https://sqlmodel.tiangolo.com/tutorial/fastapi/simple-hero-api/#create-database-and-tables-on-startup)
In this way, when executing the app with the command "uvicoirn main:app --reload" the database and tables are immediately created.
I tried to do it, but it generates an error, precisely because of the "starup" event. The shell tells me that this event (which apparently comes from starlette) needs other arguments.
I appreciate any help.
![Captura desde 2023-01-24 11-29-51](https://user-images.githubusercontent.com/52362114/214353396-22ff20b3-2b02-437a-a316-3d51570fcf7b.png)

![Captura desde 2023-01-24 11-36-33](https://user-images.githubusercontent.com/52362114/214352845-b3984a09-b223-4e50-9c9d-6c584c54e838.png)

**Comment by jod35** [comment]
Thanks so much! Didn't think of it at the time of recording the video
